name: flutter_projects
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^2.0.3
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  image_picker: ^0.8.6
  cookie_jar: ^3.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  onesignal_flutter: ^5.1.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/part_time_connect_logo.png
    -  fonts/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
