# Generated by Django 5.1.4 on 2025-02-28 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_recommendation_score_and_more'),
        ('jobs', '0003_job_benefits_job_contract_pdf_job_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Offered', 'Offered')], default='Applied', max_length=20)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('contract_viewed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.userprofile')),
            ],
        ),
    ]
