# Generated by Django 5.1.4 on 2025-03-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_full_name'),
        ('jobs', '0005_recruitercontact_recruiterview_shortlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('SAVE', 'Save'), ('APPLY', 'Apply')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userregistration')),
            ],
        ),
    ]
