# Generated by Django 5.1.4 on 2025-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_companyregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyregistration',
            name='photo',
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
