# Generated by Django 5.1.4 on 2025-02-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userregistration_engagement_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='engagement_score',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='feedback_score',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='popularity_score',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('education_certifications', models.JSONField(default=list)),
                ('languages_spoken', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('portfolio', models.JSONField(default=list)),
                ('engagement_score', models.FloatField(default=0)),
                ('popularity_score', models.FloatField(default=0)),
                ('feedback_score', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.userregistration')),
            ],
        ),
    ]
