# Generated by Django 5.1.4 on 2025-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userregistration_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommendation_score',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience',
        ),
    ]
