# Generated by Django 5.1.4 on 2025-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_contacts_userprofile_profile_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
    ]
