# Generated by Django 5.1.7 on 2025-03-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_companyregistration_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resumes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
