# Generated by Django 5.1.5 on 2025-01-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userregistration_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='full_name',
            new_name='username',
        ),
    ]
