# Generated by Django 5.1.5 on 2025-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_jobtype_workplaceimage_remove_company_job_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='jobTypes',
        ),
        migrations.AddField(
            model_name='company',
            name='job_types',
            field=models.ManyToManyField(to='accounts.jobtype'),
        ),
    ]
