# Generated by Django 5.1.5 on 2025-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_company_jobtypes_company_job_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_types',
        ),
        migrations.AddField(
            model_name='company',
            name='jobTypes',
            field=models.ManyToManyField(to='accounts.jobtype'),
        ),
    ]
