# Generated by Django 5.1.5 on 2025-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_company_job_types_company_jobtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobTypes',
            field=models.ManyToManyField(blank=True, to='accounts.jobtype'),
        ),
    ]
