# Generated by Django 5.1.5 on 2025-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_company_jobtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='jobTypes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workplace_images',
        ),
        migrations.AddField(
            model_name='company',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='WorkplaceImage',
        ),
    ]
