# Generated by Django 5.1.5 on 2025-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_jobtype_workplaceimage_remove_company_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
