# Generated by Django 5.1.5 on 2025-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('jobtype', models.CharField(max_length=200)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='jobTypes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workplace_images',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='resume',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='resumes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='WorkplaceImage',
        ),
    ]
