# Generated by Django 5.1.4 on 2025-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('delivered', 'Delivered')], default='unread', max_length=20),
        ),
    ]
