# Generated by Django 5.1.4 on 2025-04-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_customtoken'),
        ('chat', '0002_message_attachment_message_deleted_and_more'),
        ('jobs', '0007_alter_jobinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('application', 'Job Application'), ('profile_view', 'Profile View Notification')], default='text', max_length=50),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_user', 'receiver_user'], name='chat_messag_sender__8fda63_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_company', 'receiver_user'], name='chat_messag_sender__b160b2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
    ]
