# Generated by Django 5.1.4 on 2025-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_message_related_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('recipient_type', models.CharField(max_length=10)),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(max_length=10)),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('application', 'Job Application'), ('profile_view', 'Profile View')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.IntegerField(null=True)),
            ],
        ),
    ]
