# Generated by Django 5.1.4 on 2025-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userregistration_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='engagement_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='feedback_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
