# Generated by Django 5.1.4 on 2025-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_recommendation_score_and_more'),
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.ManyToManyField(related_name='user_experience', to='jobs.jobapplication'),
        ),
    ]
