# Generated by Django 5.1.4 on 2025-03-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='resumes',
            new_name='resumes_json',
        ),
    ]
