# Generated by Django 5.1.4 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_companyregistration_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='user_type',
            field=models.CharField(default='JobProvider', max_length=20),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_type',
            field=models.CharField(default='JobSeeker', max_length=20),
        ),
    ]
