# Generated by Django 5.1.4 on 2025-02-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_companyregistration_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='resume',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='resumes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
