# Generated by Django 5.1.4 on 2025-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_resumes_json_userregistration_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='user_type',
            field=models.CharField(choices=[('JobSeeker', 'Job Seeker'), ('JobProvider', 'Job Provider')], default='JobProvider', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_type',
            field=models.CharField(choices=[('JobSeeker', 'Job Seeker'), ('JobProvider', 'Job Provider')], default='JobSeeker', max_length=20),
        ),
    ]
