# Generated by Django 5.1.4 on 2025-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='previous_recommendation_score',
            field=models.FloatField(default=0),
        ),
    ]
