# Generated by Django 5.1.4 on 2025-03-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_resumes_userregistration_resumes_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='resumes_json',
            new_name='resumes',
        ),
    ]
