# Generated by Django 5.1.4 on 2025-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_applications_job_applications_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Part-Time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.CharField(default='Flexible', max_length=100),
        ),
    ]
