# Generated by Django 5.1.4 on 2025-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('IMPRESSION', 'Impression'), ('VIEW', 'View'), ('SAVE', 'Save'), ('APPLY', 'Apply')], max_length=10),
        ),
    ]
