# Generated by Django 5.1.4 on 2025-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='resume',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='resume_files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='resumes/'),
        ),
    ]
