# Generated by Django 5.1.4 on 2025-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userregistration_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='resume_files',
            new_name='resume',
        ),
    ]
