# Generated by Django 5.1.4 on 2025-03-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_companyregistration_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_locations',
            field=models.JSONField(default=list),
        ),
    ]
