# Generated by Django 5.1.4 on 2025-02-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userregistration_engagement_score_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applications',
            new_name='applications_count',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='saves',
            new_name='saves_count',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='views',
            new_name='views_count',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='job',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyregistration'),
        ),
    ]
