# Generated by Django 5.1.5 on 2025-04-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
        ('jobs', '0007_alter_jobinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinteraction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.RenameField(
            model_name='jobinteraction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='jobinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Consultation'), ('apply', 'Postulation'), ('feedback', 'Feedback')], default='view', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinteraction',
            name='nb_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobinteraction',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobinteraction',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
