# Generated by Django 5.1.5 on 2025-04-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_alter_jobinteraction_job_and_more'),
        ('jobs', '0007_alter_jobinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinteraction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_interactions', to='jobs.job'),
        ),
    ]
